#!/bin/bash

#####################################################
# Flashize                                          #
# Copyright 2016, Lanchon                           #
#####################################################

#####################################################
# Flashize is free software licensed under GNU's    #
# General Public License (GPL) version 3 and any    #
# later version.                                    #
# ------------------------------------------------- #
# The Flashize Runtime is free software licensed    #
# under GNU's Lesser General Public License (LGPL)  #
# version 3 and any later version.                  #
#####################################################

version="2016-03-23"

set -e

script="$1"
zip="$2"
log="$3"

count=3

td="/tmp/lanchon-flashize"

error() {
    >&2 echo "$@"
}

fatal() {
    error "$@"
    exit 1
}

if [ "$zip" == "-" ]; then zip=""; fi
if [ "$log" == "-" ]; then log=""; fi

if  [ -z "$script" ] || ([ "$script" == "-" ] && [ -z "$zip" ]) || [ $# -gt $count ]; then
    error "Flashize ($version)"
    error
    error "Converts a shell script to a flashable Android recovery zip."
    error
    error "Usage: <input-script> [<output-zip> [<runtime-logfile>]]"
    error
    error "Reads the script from standard input if <input-script> is a dash (-)."
    error
    error "Names the output zipfile based on <input-script> if <output-zip> is null or a dash."
    error
    error "Can create a logfile on the device at runtime, according to the value of <runtime-logfile>:"
    error "  -The absolute path of the logfile to be created."
    error "  -A relative path or filename to be interpreted against the path of the zipfile being run."
    error "  -A dot (.) to use the pathname of the zipfile being run with a '.log' extension."
    error "  -Null or a dash to disable logging."
    error
    error "Script debugging modes are enabled by creating dummy files on the target device:"
    error "  -Create '/tmp/flashize-debug' to trace the user-supplied script."
    fatal
fi

if [ "$script" != "-" ] && [ ! -f "$script" ]; then
    fatal "error: script not found"
fi

if [ -z "$zip" ]; then
    zip="$(dirname "$script")/$(basename "$script" .sh).zip"
fi

wd="$td/META-INF/com/google/android"
ubin="$wd/update-binary"
uscr="$wd/updater-script"

rm -rf "$td"
mkdir -p "$wd"

cat >"$ubin" <<EOF
#!/sbin/sh

#####################################################
# Flashize Runtime (${version})                     #
# Copyright 2016, Lanchon                           #
#####################################################

#####################################################
# The Flashize Runtime is free software licensed    #
# under GNU's Lesser General Public License (LGPL)  #
# version 3 and any later version.                  #
# ------------------------------------------------- #
# Note: The code appended to the Flashize Runtime,  #
# if any, is independently licensed.                #
#####################################################

EOF
cat >>"$ubin" <<"EOF"
if [ "$1" != "lanchon-magic" ]; then
EOF
cat >>"$ubin" <<EOF
    export FLASHIZE_VERSION="$version"
    log="$log"
EOF
cat >>"$ubin" <<"EOF"
    out="/proc/self/fd/$2"
    zip="$3"
    if [ -n "$log" ]; then
        if [ "${log::1}" != "/" ]; then
            logzip="$zip"
            if [ "$logzip" == "/tmp/update.zip" ] || [ "$logzip" == "/sideload/package.zip" ]; then
                # if sideloading, for relative logfile naming purposes pretend that the zip is:
                logzip="/tmp/sideload.zip"
            fi
            if [ "$log" == "." ]; then
                log="$(basename "$logzip" .zip).log"
            fi
            log="$(dirname "$logzip")/$log"
        fi
        mkdir -p "$(dirname "$log")"
    fi
    print() {
        local s="$1"
        if [ -n "$log" ]; then
            >>"$log" echo "$s"
        fi
        if [ -z "$s" ]; then s=" "; fi
        >$out echo "ui_print $s"
        >$out echo "ui_print"
    }
    print
    if [ -n "$log" ]; then
        >"$log"
    fi
    set -o pipefail
    /sbin/sh "$0" "lanchon-magic" "$zip" 2>&1 | (
        IFS=""
        while read -r line; do print "$line"; done
    )
    code="$?"
    print
    if [ "$code" -eq "0" ]; then
        print "[OK]";
    else
        print "[ERROR $code]";
    fi
    log=""
    print
    exit "$code"
fi
shift
[ ! -f /tmp/flashize-debug ] || set -x

#####################################################

EOF

cat >"$uscr" <<EOF
#####################################################
# Powered by Lanchon's Flashize                     #
#####################################################
EOF

cat "$script" >>"$ubin"

zip="$(readlink -f "$zip")"
cd "$td"
zip -r9q "$zip" .
rm -rf "$td"
