#!/bin/bash

{

set -e

rm -f twrp-env/*

./make-env-from-twrp    twrp-img/arm/twrp-2.8.7.1-hammerhead.img    -   twrp2-arm       extras/parted
./make-env-from-twrp    twrp-img/arm/twrp-3.0.0-0-hammerhead.img    -   twrp3-arm
./make-env-from-twrp    twrp-img/arm64/twrp-2.8.7.1-clark.img       -   twrp2-arm64
./make-env-from-twrp    twrp-img/arm64/twrp-3.0.0-1-clark.img       -   twrp3-arm64
./make-env-from-twrp    twrp-img/x86_64/twrp-2.8.7.2-Z00A.img       -   twrp2-x86_64
./make-env-from-twrp    twrp-img/x86_64/twrp-3.0.0-0-Z00A.img       -   twrp3-x86_64

} 2>&1 | tee make-twrp.log
