#!/bin/bash

set -e

dir="$1"
zip="$2"

td=/tmp/flashize-env-make-zip
tfiles=$td/files
base=$tfiles/flashize
tlinks=$td/links

if [ $# -ne 2 ]; then
    >&2 echo "Usage: <input-dir> <output-zip>"
    exit 1
fi

rm -f "$zip"

rm -rf $td
mkdir -p $td

cp -rd "$dir" $tfiles
cp -rd $base $tlinks

find $base -type l -delete
find $tlinks \! -type d \! -type l -delete
find $tlinks -type d -empty -delete

pushd $tlinks >/dev/null
find . -depth -print0 | cpio -o --null --format=newc --quiet >$base/env-setup/symlinks.cpio
popd >/dev/null

cat >>$base/env-setup/post-extract <<"EOF"
# Workaround for busybox unzip being unable to extract symlinks:
cpio -id <env-setup/symlinks.cpio 2>/dev/null
if [ $? -ne 0 ]; then
    >&2 echo "flashize-env: setup-pre: unable to extract symlinks"
    exit 1
fi
rm env-setup/symlinks.cpio

# Workaround for signapk removing empty folders messing with permissions:
mkdir -p env/sbin env/sbin-extra
chmod -R +rx env/sbin env/sbin-extra

EOF

zip="$(readlink -f "$zip")"
cd "$tfiles"
zip -r9q "$zip" .
rm -rf "$td"
